package managers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class CakeManager {
	
	private Connection con;
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	
	private String createTableCake = "CREATE TABLE Cake(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(40), price decimal)";
	private Statement stm;
	
	
	public CakeManager() {
		try {
			con = DriverManager.getConnection(url);
			stm = con.createStatement();
			
			ResultSet rs = con.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			
			while(rs.next()){
				if("Cake".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;					
				}
			}
			if(!tableExists)
				stm.executeUpdate(createTableCake);			
		} catch(SQLException e) {
			e.printStackTrace();
		}		
	}
	
	public Connection getConnection() {
		return con;
	}
	
	
	
}
